name: Notify Documentation Repository

on:
  push:
    branches:
      - dev
jobs:
  notify-documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Documentation Update
      run: |
        repo_name="source-repo-name"
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.TARGET_REPO_PAT }}" \
          https://api.github.com/repos/ddanielgc/static-documentation-stack/dispatches \
          -d "{\"event_type\":\"update-docs\",\"client_payload\":{\"repo_name\":\"${repo_name}\"}}"
      env:
        TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}